default: &default
  adapter: postgresql
  encoding: unicode
  database: RT_def
  pool: 5
  username: <%= ENV['RT_DATABASE_USER'] %>
  password: <%= ENV['RT_DATABASE_PASSWORD'] %>
development:
  adapter: postgresql
  encoding: unicode
  database: RT_dev
  pool: 5
  username: <%= ENV['RT_DATABASE_USER'] %>
  password: <%= ENV['RT_DATABASE_PASSWORD'] %>
  
test:
  adapter: postgresql
  encoding: unicode
  database: RT_test
  pool: 5
  username: <%= ENV['$RT_DATABASE_USER'] %>
  password: <%= ENV['$RT_DATABASE_PASSWORD'] %>
production:
  adapter: postgresql
  encoding: unicode
  database: RT_prod
  pool: 5
  username: <%= ENV['RT_DATABASE_USER'] %>
  password: <%= ENV['RT_DATABASE_PASSWORD'] %>
